### ISSUE TITLE
Exception: No submit queue specified

### ISSUE THREAD

**Issue by EmilyWesel** [amcpherson/destruct#2]
I have tried running destruct with the following command: 

./destruct run /u/flashscratch/e/emilyewe/testData/chr19_new.fa break break2 break3 --bam_files /u/flashscratch/e/emilyewe/testData/LP_J.chr19.1.25p.5_sorted.bam /u/flashscratch/e/emilyewe/testData/LP_J.chr19.1.25p.5_sorted.header.bam --lib_ids tumour normal --tmpdir tempdir

I receive the following error: raise Exception('No submit queue specified')
Exception: No submit queue specified

I would like to run destruct for deletions only. 

How do I fix this so that destruct can run?

Thanks, 
Emily

**Comment by amcpherson** [comment]
You need to specify how jobs are submitted, easiest is —submit local

**Comment by EmilyWesel** [comment]
Hello, 

Thanks for your helpful response!

I added --submit local, so my command is now ./destruct run /u/flashscratch/e/emilyewe/testData/chr19_new.fa break break2 break3 --bam_files /u/flashscratch/e/emilyewe/testData/LP_J.chr19.1.25p.5_sorted.bam /u/flashscratch/e/emilyewe/testData/LP_J.chr19.1.25p.5_sorted.header.bam --lib_ids tumour normal --tmpdir tempdir --submit local

Although --submit local has solved the submit queue error, I am now receiving a pipeline failed error even after install pytables. 

Here's the complete output:
2018-07-20 13:52:59,283 - pypeliner.execqueue - ERROR - /bylibrary:normal/bamdisc submit failed
	---------- delegator command ----------
	pypeliner_delegate /u/home/e/emilyewe/.conda/envs/my_pymc_env/bin/tempdir/log/20180720-135249/bylibrary/normal/bamdisc/exc0/job.dgt.before /u/home/e/emilyewe/.conda/envs/my_pymc_env/bin/tempdir/log/20180720-135249/bylibrary/normal/bamdisc/exc0/job.dgt.after /u/home/e/emilyewe/.conda/envs/my_pymc_env/lib/python2.7/site-packages/destruct-0.4.9-py2.7.egg/destruct
	[Errno 2] No such file or directory
	---------- job stderr ----------
	---------- job stdout ----------
2018-07-20 13:52:59,298 - pypeliner.scheduler - ERROR - exception
	Traceback (most recent call last):
	  File "/u/home/e/emilyewe/.conda/envs/my_pymc_env/lib/python2.7/site-packages/pypeliner/scheduler.py", line 76, in run
	    self._add_jobs(exec_queue, workflow, runskip)
	  File "/u/home/e/emilyewe/.conda/envs/my_pymc_env/lib/python2.7/site-packages/pypeliner/scheduler.py", line 130, in _add_jobs
	    self._add_job(exec_queue, job)
	  File "/u/home/e/emilyewe/.conda/envs/my_pymc_env/lib/python2.7/site-packages/pypeliner/scheduler.py", line 112, in _add_job
	    exec_queue.send(job.ctx, job.displayname, sent, exc_dir)
	  File "/u/home/e/emilyewe/.conda/envs/my_pymc_env/lib/python2.7/site-packages/pypeliner/execqueue/subproc.py", line 28, in send
	    submitted = self.create(ctx, name, sent, temps_dir)
	  File "/u/home/e/emilyewe/.conda/envs/my_pymc_env/lib/python2.7/site-packages/pypeliner/execqueue/local.py", line 56, in create
	    return LocalJob(ctx, name, sent, temps_dir, self.modules)
	  File "/u/home/e/emilyewe/.conda/envs/my_pymc_env/lib/python2.7/site-packages/pypeliner/execqueue/local.py", line 34, in __init__
	    raise pypeliner.execqueue.base.SubmitError()
	SubmitError
2018-07-20 13:52:59,298 - pypeliner.scheduler - ERROR - pipeline failed
log file: tempdir/log/20180720-135249/pipeline.log
Traceback (most recent call last):
  File "./destruct", line 11, in <module>
    load_entry_point('destruct==0.4.9', 'console_scripts', 'destruct')()
  File "/u/home/e/emilyewe/.conda/envs/my_pymc_env/lib/python2.7/site-packages/destruct-0.4.9-py2.7.egg/destruct/ui/main.py", line 16, in main
  File "/u/home/e/emilyewe/.conda/envs/my_pymc_env/lib/python2.7/site-packages/destruct-0.4.9-py2.7.egg/destruct/ui/run.py", line 31, in run
  File "/u/home/e/emilyewe/.conda/envs/my_pymc_env/lib/python2.7/site-packages/pypeliner/app.py", line 221, in run
    self.sch.run(workflow, self.exec_queue, self.file_storage, self.runskip)
  File "/u/home/e/emilyewe/.conda/envs/my_pymc_env/lib/python2.7/site-packages/pypeliner/scheduler.py", line 97, in run
    raise PipelineException('pipeline failed')
pypeliner.scheduler.PipelineException: pipeline failed

Thanks,
Emily

**Comment by amcpherson** [comment]
Somethings wrong with your installation. Try running the delegator command,
if that doesn’t work figure out why Pypeliner isn’t installed correctly
